sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss: # 写自己的阿里云oss服务器信息，不过我没有。。
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPeFLzPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3nXbu1GTUzy6Pd7
    bucket-name: sky-itcast
